FORMAT: 1A
HOST: http://metrics.brightcove.com

# Brightcove Data Collection API

The Data Collection API allows you to add events to your Video Cloud Analytics data in situations where Brightcove cannot track the events directly. Please contact your account manager if you are interested in using this API.

## Base URL

The base URL for the Data Collection API is:

    http://metrics.brightcove.com

# Group Event Tracker

## Event tracking [/tracker{?account}{&domain}{&event}{&player}{&player_name}{&video}{video_name}{&time}{&video_duration}{&range}{&video_seconds_viewed}{&desination}{&source}{&device_type}{&device_os}{&country}{&country_name}{&region}{&region_name}{&city}{&dma}]

+ Parameters
    + account (required, number, `1234567`) ... Numeric Video Cloud account ID
    + domain (required, string, `videocloud`) ... String always equal to `videocloud`
    + event (required, string, `video_view`) ... String the analytics event tracked
        + values
            + `player_load`
            + `video_impression`
            + `video_view`
            + `video_engagement`
    + player (optional, string, `1234567`) ... 
    
### Track an event [GET]
+ Response 200 (application/json)

        (returns a 1x1 transparent gif image)

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
