FORMAT: 1A
HOST: http://metrics.brightcove.com

# Brightcove Data Collection API

The Data Collection API allows you to add events to your Video Cloud Analytics data in situations where Brightcove cannot track the events directly. Please contact your account manager if you are interested in using this API. See [Video Cloud Analytics Event Tracking](http://docs.brightcove.com/en/video-cloud/analytics-api/video-view-tracking.html#video_engagement-events) for more information.

## Base URL

The base URL for the Data Collection API is:

    http://metrics.brightcove.com

# Group Event Tracker

## Event tracking [/tracker{?account}{&domain}{&event}{&player}{&player_name}{&video}{video_name}{&time}{&video_duration}{&range}{&video_seconds_viewed}{&destination}{&source}{&device_type}{&device_os}{&country}{&country_name}{&region}{&region_name}{&city}{&dma}]

+ Parameters
    + account (required, number, `1234567`) ... Numeric Video Cloud account ID
    + domain (required, string, `videocloud`) ... Slways equal to `videocloud`
    + event (required, string, `video_view`) ... The analytics event tracked
        + values
            + `player_load`
            + `video_impression`
            + `video_view`
            + `video_engagement`
    + player (optional, string, `1234567`) ... Unique ID for the player
    + player_name (optional, string, `Large VideoJS Player`) ... Name for the player
    + video (optional, string, `1234567`) ... The Video Cloud ID of the video
    + video_name (optional, string, `My Short Video`) ... The name of the video
    + time (optional, number, `1400774757123`) ... The timestamp for the event (epoch time in ms)
    + video_duration (optional, number, `360.275`) ... The duration of the video in seconds
    + range (optional, string, `20..30`) ... The range of the video video viewed for `video_engagement` events in the format `StartSecond..EndSecond`
    + video_seconds_viewed (optional, number, `10.25`) ... A count of watched seconds since the last update for `video_engagement` events
    + destination (optional, string, `http://mysite.com/videos/latest-videos.html`) ... The URI that originated the event
    + source (optional, string, `http://mysite.com/index.html`) ... The URI that sent the end-user to the `destination` URI
    + device_type (optional, string, `mobile`) ... Override to specify the type of the device that originated the event in cases where the User-Agent is unreliable; ignored unless both `device_os` and `device_type` are included or if the value submitted does not match the list of values here. **Not typically included**
        + values
            + direct
            + mobile
            + tablet
            + tv
            + desktop
            + other
    + device_os (optional, string, `ios`) ... Override to specify the OS of the device that originated the event in cases where the User-Agent is unreliable; ignored unless both `device_os` and `device_type` are included. **Not typically included**
    + country (optional, string, `US`) ... ISO-3166 (alpha 2) country code (override in case the system can not detect geographic information from the IP address)
    + country_name (optional, string, `United States`) ... Human readable country name (override in case the system can not detect geographic information from the IP address)
    + region (optional, string, `US-WA`) ... ISO-3166 (alpha 2) region code (override in case the system can not detect geographic information from the IP address)
    + region_name (optional, string, `Washington`) ... Human readable region name (override in case the system can not detect geographic information from the IP address)
    + city (optional, string, `Seattle`) ... City name
    + dma (optional, number, `511`) ... numeric [DMA](https://support.google.com/richmedia/answer/2745487?hl=en) code
    
### Track an event [GET]
+ Response 200 (application/json)

        (returns a 1x1 transparent gif image)

